import Head from 'next/head'
import { FC, ReactNode } from 'react'

import { Footer } from 'src/components/organisms/Footer'
import { Header } from 'src/components/organisms/Header'

type Props = {
  title: string
  children: ReactNode
}

export const Template: FC<Props> = ({ title, children }) => (
  <div>
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    {children}
    <Footer />
  </div>
)
